// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const isMigrationCommand = process.argv.includes("migrate");

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: isMigrationCommand ? env("DIRECT_URL") : env("DATABASE_URL"),
  },
});
